// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9peaw9hJtjlWIK_d1ZA_jsHw9cBKsrfY',
    appId: '1:553751005160:web:4ee34add096d4bf7fbc65d',
    messagingSenderId: '553751005160',
    projectId: 'fitt-4bf22',
    authDomain: 'fitt-4bf22.firebaseapp.com',
    storageBucket: 'fitt-4bf22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuXjFdd6aJqZN7sUyd90ODq9gmZZ-vzMY',
    appId: '1:553751005160:android:048a4520711bd875fbc65d',
    messagingSenderId: '553751005160',
    projectId: 'fitt-4bf22',
    storageBucket: 'fitt-4bf22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD82ubNpSXCA_M2MNkIYl1BF3EWgWmkDNY',
    appId: '1:553751005160:ios:a908141b910c39f8fbc65d',
    messagingSenderId: '553751005160',
    projectId: 'fitt-4bf22',
    storageBucket: 'fitt-4bf22.appspot.com',
    iosBundleId: 'com.example.fitTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD82ubNpSXCA_M2MNkIYl1BF3EWgWmkDNY',
    appId: '1:553751005160:ios:a908141b910c39f8fbc65d',
    messagingSenderId: '553751005160',
    projectId: 'fitt-4bf22',
    storageBucket: 'fitt-4bf22.appspot.com',
    iosBundleId: 'com.example.fitTry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9peaw9hJtjlWIK_d1ZA_jsHw9cBKsrfY',
    appId: '1:553751005160:web:066006577423078afbc65d',
    messagingSenderId: '553751005160',
    projectId: 'fitt-4bf22',
    authDomain: 'fitt-4bf22.firebaseapp.com',
    storageBucket: 'fitt-4bf22.appspot.com',
  );
}
